stages:
  - deploy

variables:
  APP_DIR: /opt/app

deploy_to_ec2:
  stage: deploy
  tags: 
    - arm-runner  
  only:
    - main
  script:
    - echo "Započinjem deployment Node.js aplikacije..."
    
    # 1. Kopiranje koda na server preko rsync-a
    - sudo rsync -av --delete --exclude='.git' --exclude='node_modules' --exclude='terraform' ./ $APP_DIR/
    
    # 2. Postavljanje dozvola nad aplikativnim folderom
    - sudo chown -R ubuntu:ubuntu $APP_DIR
    
    # 3. Build-ovanje nove Node.js Docker slike
    - cd $APP_DIR
    - sudo docker build -t arm_node_web:latest .
    
    # 4. Sigurno gašenje i brisanje prethodnog kontejnera ako postoji
    - sudo docker stop arm_frontend || true
    - sudo docker rm arm_frontend || true
    
    # 5. Pokretanje NOVOG kontejnera unutar Docker mreže na portu 3000
    - sudo docker run -d --name arm_frontend -p 3000:3000 --env-file /etc/app.env --restart always arm_node_web:latest
    
    # 6. OSVJEŽAVANJE I SIGURNOST APACHE KONFIGURACIJE
    - sudo cp $APP_DIR/www.conf /etc/apache2/sites-available/node_app.conf || true
    - sudo a2enmod proxy proxy_http ssl || true
    - sudo a2dissite 000-default default-ssl || true
    - sudo a2ensite node_app.conf || true
    
    # 7. Restart Apache-a da prihvati novu konfiguraciju i sertifikate
    - sudo systemctl restart apache2
    
    # Privremeno rješenje dok rsync ne prebaci sve fajlove
    - sudo systemctl restart apache2 || true
    
    - echo "Node.js aplikacija je uspješno podignuta na HTTPS protokolu!"
  environment:
    name: production