stages:
  - deploy

deploy_to_ec2:
  stage: deploy
  tags: 
    - arm-runner  
  script:
    - echo "Započinjem deploy sa GitLab Runnera..."
    
    - sudo rsync -av --delete --exclude='.git' --exclude='node_modules' --exclude='terraform' ./ /opt/app/
    
    - sudo chown -R gitlab-runner:gitlab-runner /opt/app
    - sudo chmod -R 775 /opt/app
    
    - sudo /opt/deploy.sh
    
    - sudo cp /opt/app/www.conf /etc/apache2/sites-available/www.conf
    - sudo a2ensite www.conf
    - sudo systemctl reload apache2
    
    - echo "Deployment uspješno završen!"
  environment:
    name: production